# 1、神经网络数据表示

**标量(0D张量)**  
仅包含一个数字的张量叫做标量，ndim = 0

In [1]:
import numpy as np

x = np.array(12)
x 

array(12)

In [2]:
x.ndim

0

**向量(1D张量)**  
数组组成的数组叫向量（vector），ndim = 1

In [3]:
x = np.array([1, 2, 3, 4 , 5])
x

array([1, 2, 3, 4, 5])

In [4]:
x.ndim

1

**矩阵(2D张量)**  
向量组成的数组叫作矩阵（matrix），ndim = 2

In [5]:
x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
x.ndim

2

**3D张量与高维张量**

In [7]:
x = np.array([[[1, 2],
               [1, 2]],
              [[3, 4],
               [3, 4]],
              [[5, 6],
               [5, 6]]])
x

array([[[1, 2],
        [1, 2]],

       [[3, 4],
        [3, 4]],

       [[5, 6],
        [5, 6]]])

In [8]:
x.ndim

3

**查看数据的数据类型和形状**  

In [9]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
# 形状
x.shape

(2, 3)

In [10]:
# 数据类型
x.dtype

dtype('int32')

# 2、数据操作

**切片 Slice**

In [13]:
x = np.array([[[1, 2],
               [1, 2]],
              [[3, 4],
               [3, 4]],
              [[5, 6],
               [5, 6]]])
x_slice = x[1:3]
x_slice

array([[[3, 4],
        [3, 4]],

       [[5, 6],
        [5, 6]]])

In [14]:
x_slice.shape

(2, 2, 2)

**数据批量**  
机器学习中，有时不会处理整个数据集，而是将数据拆分为小批量，比如一个批量为128，batch = 128。  
一般，第一个轴叫做 批量轴  
**逐元素运算**

In [5]:
import numpy as np  
# 逐元素相加
x = np.array([1, 1, 1, 1, 1]) 
y = np.array([0, 1, 2, 3, 4])
z = x + y
z 

array([1, 2, 3, 4, 5])

In [6]:
# 点积
z = np.dot(x, y)
z

10

**张量变形**  
张量变形是指改变张量的行和列，变形后的张量的元素总个数与初始张量相同  

In [7]:
x = np.array([[1, 2],
              [3, 4],
              [5, 6]])  
x.shape

(3, 2)

In [8]:
x = x.reshape((6, 1)) 
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [9]:
x = x.reshape((2,3))
x 

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 转置 transposition, 行列互换
x = np.zeros((300, 20))
x = np.transpose(x) 
x.shape

(20, 300)